feat: add methods for replacing placeholders
crowdin/ota-client-js pull request #31
Opened 2022-02-05 18:27 UTC by ImRodry

This PR adds 3 new methods to the library to make it easier to retrieve raw data such as replaced URLs, full language objects and language codes in a specific format. Tests for all methods were added and are passing, but if you think there are better ways to implement these methods, please let me know!

2022-02-07 07:49 UTC, andrii-bodnar commented
Hi @ImRodry, thanks a lot for your contribution!

2022-02-07 14:18 UTC, yevheniyJ requested changes
Thanks a lot! But could you please add those new methods to the README?

2022-02-07 15:10 UTC, ImRodry commented
Absolutely! I thought of that but it completely slipped my mind in the end. Will do now

2022-02-08 18:31 UTC, yevheniyJ approved these changes

2022-02-08 18:31 UTC, merged